name: rings
description: A Flutter application for the Rings bank

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2

  get: 4.3.4
  hasura_connect: 3.0.4
  dartz: 0.10.0-nullsafety.2
<<<<<<< HEAD:frontend/pubspec.yaml
  jwt_decoder: 2.0.1
=======
  easy_mask: ^2.0.1
>>>>>>> signup:pubspec.yaml

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
