version: '3.8'

services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:latest.cli-migrations-v3
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    external_links:
      - hasura_node_auth:node_auth
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    env_file:
      - .hasura.env

  hasura_node_auth:
    build:
      context: node
    depends_on:
    - "graphql-engine"
    ports:
      - 8000:8000
    restart: always
    external_links:
      - graphql-engine:hasura
    environment:
      SERVER_PORT: 8000
      JWT_SECRET: Tj2srXEL67sN9CNAsga5XcU99GHA55VV
      HASURA_GRAPHQL_URL: http://hasura:8080/v1/graphql
      HASURA_ADMIN_SECRET: QYje56evpvZJgYU9vqu8wMbRaZMRR9UH
    command: npm start

volumes:
  db_data:
